<?php
include 'secure_page_template.php'; 
include 'db_connect.php'; 

// === PERMISSION CHECK: MANAGER/ADMIN ONLY ===
if (!check_permission([ROLE_ADMIN, ROLE_MANAGER])) {
    header("Location: index.php?error=permission");
    exit;
}
// ==========================

// Fetch the latest forecast data
$sql_forecast = "
    SELECT 
        DF.Forecast_Month, 
        DF.Predicted_Demand, 
        DF.Forecast_Date,
        P.Name AS ProductName,
        P.Stock_Quantity AS CurrentStock,
        P.Unit
    FROM 
        DEMAND_FORECAST DF
    JOIN 
        PRODUCTS P ON DF.Product_ID = P.Product_ID
    WHERE
        DF.Forecast_Month >= CURDATE() -- Show forecasts for the current month onwards
    ORDER BY 
        DF.Forecast_Month ASC, P.Name ASC";
        
$result_forecast = $conn->query($sql_forecast);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demand Forecast Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --forecast: #06b6d4; /* Info color for forecast */
            --primary: #4f46e5;
            --success: #10b981;
            --warning: #f59e0b;
        }
        body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; font-family: 'Inter', sans-serif; }
        .container-main { max-width: 1200px; margin: 2rem auto; padding: 0 1rem; }
        .page-header { background: white; border-radius: 1.5rem; padding: 2rem; margin-bottom: 2rem; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); }
        .page-header h1 { color: var(--forecast); font-weight: 700; margin: 0 0 0.5rem 0; display: flex; align-items: center; gap: 1rem; }
        .table-card { background: white; border-radius: 1.5rem; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); overflow: hidden; }
        .table-modern thead th { background: #f1f5f9; color: #475569; font-weight: 700; padding: 1.25rem 1.5rem; }
        .table-modern tbody tr:hover { background: #f8fafc; }
        .demand-value { font-size: 1.1rem; font-weight: 700; color: var(--primary); }
        .reorder-needed { background: #fef3c7; color: #92400e; font-weight: 600; padding: 5px 10px; border-radius: 5px; }
        .stock-ok { background: #d1fae5; color: #065f46; font-weight: 600; padding: 5px 10px; border-radius: 5px; }
        .btn-forecast-trigger { background: linear-gradient(135deg, var(--forecast), #0891b2); color: white; }
        .btn-forecast-trigger:hover { color: white; }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid px-4">
            <a class="navbar-brand" href="index.php">
                <i class="fas fa-chart-line me-2"></i>Billing System
            </a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="invoice_form.php">
                            <i class="fas fa-file-invoice me-2"></i>New Invoice
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item me-3 d-flex align-items-center">
                        <span class="navbar-text text-white-50">
                            <i class="fas fa-user-circle me-1"></i> Logged in as: 
                            <strong><?= htmlspecialchars($_SESSION['username']) ?></strong>
                            (<?= htmlspecialchars($_SESSION['role']) ?>)
                        </span>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-sm btn-danger" href="logout.php">
                            <i class="fas fa-sign-out-alt me-2"></i>Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-main">
        
        <div class="page-header">
            <h1><i class="fas fa-magic"></i> AI Demand Forecast Results</h1>
            <p class="text-muted">Predictions generated by the external ML service show expected stock needs for upcoming months.</p>
            <div class="d-flex justify-content-end gap-3">
                <a href="reports.php" class="btn btn-outline-secondary">
                    <i class="fas fa-arrow-left me-2"></i> Back to Reports
                </a>
                <a href="export_sales_data.php" class="btn btn-forecast-trigger">
                    <i class="fas fa-download me-2"></i> Export Data for ML Model
                </a>
            </div>
        </div>

        <?php if ($result_forecast && $result_forecast->num_rows > 0): ?>
            <div class="table-card table-responsive">
                <table class="table table-modern table-striped mb-0">
                    <thead>
                        <tr>
                            <th>Forecast For</th>
                            <th>Product Name</th>
                            <th class="text-center">Predicted Demand</th>
                            <th class="text-center">Current Stock</th>
                            <th class="text-center">Stock Recommendation</th>
                            <th>Forecast Generated</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php while($row = $result_forecast->fetch_assoc()): 
                            $recommendation = $row['Predicted_Demand'] > $row['CurrentStock'] ? 
                                ($row['Predicted_Demand'] - $row['CurrentStock']) : 0;
                            $recommendation_class = $recommendation > 0 ? 'reorder-needed' : 'stock-ok';
                            $recommendation_text = $recommendation > 0 ? 
                                "Reorder: {$recommendation} {$row['Unit']}" : 
                                'Stock Level OK';
                        ?>
                        <tr>
                            <td><?= date('F Y', strtotime($row['Forecast_Month'])) ?></td>
                            <td><?= htmlspecialchars($row['ProductName']) ?></td>
                            <td class="text-center demand-value"><?= $row['Predicted_Demand'] ?> <?= htmlspecialchars($row['Unit']) ?></td>
                            <td class="text-center"><?= $row['CurrentStock'] ?> <?= htmlspecialchars($row['Unit']) ?></td>
                            <td class="text-center">
                                <span class="<?= $recommendation_class ?>">
                                    <?= $recommendation_text ?>
                                </span>
                            </td>
                            <td><?= date('d M Y H:i', strtotime($row['Forecast_Date'])) ?></td>
                        </tr>
                        <?php endwhile; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="alert alert-info text-center mt-5">
                <i class="fas fa-info-circle me-2"></i>
                No demand forecasts found. Export data and run the ML model to generate the first report.
            </div>
        <?php endif; ?>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <?php $conn->close(); ?>
</body>
</html>